[build]
builder = "DOCKERFILE"
dockerfilePath = "scraper_api/Dockerfile"
buildContext = "scraper_api"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
